version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./resources/docker/image/nodejs/Dockerfile
    command: npm run dev
    depends_on:
      - mongo
    links:
      - mongo
    volumes:
      - ./src:/usr/app/src
    ports:
      - "3000:3000"
    env_file:
      - .env
  mongo:
    image: mongo:3.2-jessie
    restart: always
    volumes:
      - ./resources/docker/volume/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
